language: python
python:
    - "2.7"
    - "3.3"
install:
    - pip install -r requirements.txt --use-mirrors
    - export PYTHONPATH=./plugins/mock_libs/:$PYTHONPATH
script: ./manage.py test --settings=earwig.settings.dev
notifications:
    email:
        - jturk@sunlightfoundation.com
        - paultag@sunlightfoundation.com
        - tneale@sunlightfoundation.com
