language: python
python:
    - "2.7"
install: pip install -r requirements.txt --use-mirrors
script: ./manage.py test --settings=earwig.settings.dev
notifications:
    email:
        - jturk@sunlightfoundation.com
        - paultag@sunlightfoundation.com
        - tneale@sunlightfoundation.com
