language: python
python:
    - "2.7"
    - "3.3"
install: pip install -r requirements.txt --use-mirrors
script: ./manage.py test --settings=earwig.settings.dev
matrix:
    allow_failures:
        - python: "3.3"
notifications:
    email:
        - jturk@sunlightfoundation.com
        - paultag@sunlightfoundation.com
        - tneale@sunlightfoundation.com
